language:
  - python

python:
  - "2.7"
  - "3.4"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - "nosetests --cover-package=nlp --with-coverage"

after_success:
  - coveralls

notifications:
  slack: shiraco:c0bbZXum5ZgJWORGvxMXf9jD
